# Generated by Django 4.0.2 on 2022-03-31 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_alter_images_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
