# Generated by Django 4.0.2 on 2022-05-07 19:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
