# Generated by Django 4.0.2 on 2022-06-14 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_subscribe_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Opportunie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pic', models.ImageField(upload_to='media')),
                ('Description', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
