# Generated by Django 4.0.2 on 2022-06-14 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_daily_opportunie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daily_opportunie',
            old_name='Description',
            new_name='description',
        ),
    ]
