# Generated by Django 4.0.2 on 2022-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_rename_description_daily_opportunie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_opportunie',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
