# Generated by Django 4.0.2 on 2022-06-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_vacancies',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job_vacancies',
            name='job_description',
            field=models.TextField(max_length=300),
        ),
    ]
