# Generated by Django 4.0.2 on 2022-06-23 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_vacancies_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_vacancies',
            name='deadline',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
