# Generated by Django 4.0.2 on 2022-06-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='flier_1',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='programs',
            name='flier_2',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='programs',
            name='flier_3',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='programs',
            name='flier_4',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='programs',
            name='flier_5',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='programs',
            name='guests',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='programs',
            name='topic',
            field=models.TextField(max_length=100),
        ),
    ]
