# Generated by Django 4.0.2 on 2022-06-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_programs_flier_1_programs_flier_2_programs_flier_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
