# Generated by Django 4.0.2 on 2022-06-27 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_programs_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fellowship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='media')),
                ('role', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Online_course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='media')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=50)),
                ('pic', models.ImageField(upload_to='media')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('link', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
