# Generated by Django 4.0.2 on 2022-07-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0020_alter_daily_opportunie_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programs',
            old_name='topic',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='birthday',
        ),
    ]
