# Generated by Django 4.0.2 on 2022-07-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0021_rename_topic_programs_theme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programs',
            name='link_caption',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='programs',
            name='venue',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
