# Generated by Django 4.0.2 on 2022-07-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0022_programs_link_caption_programs_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='title',
        ),
    ]
