# Generated by Django 4.0.2 on 2022-07-11 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0024_alter_programs_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programs',
            new_name='Information_session',
        ),
    ]
