# Generated by Django 4.0.2 on 2022-07-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0025_rename_programs_information_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capacity_development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField(max_length=100)),
                ('venue', models.TextField(max_length=100, null=True)),
                ('guests', models.TextField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=500)),
                ('link_caption', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(max_length=700, null=True)),
                ('flier_1', models.ImageField(null=True, upload_to='media')),
                ('flier_2', models.ImageField(null=True, upload_to='media')),
                ('flier_3', models.ImageField(null=True, upload_to='media')),
                ('flier_4', models.ImageField(null=True, upload_to='media')),
                ('flier_5', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
