# Generated by Django 4.0.2 on 2022-07-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0026_capacity_development'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacity_development',
            name='flier_4',
        ),
        migrations.RemoveField(
            model_name='capacity_development',
            name='flier_5',
        ),
    ]
