# Generated by Django 4.0.2 on 2022-07-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0027_remove_capacity_development_flier_4_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capacity_development',
            name='link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
