# Generated by Django 4.0.2 on 2022-07-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0028_alter_capacity_development_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='job_title',
            new_name='team',
        ),
    ]
