# Generated by Django 4.0.2 on 2022-07-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0029_rename_job_title_team_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
            ],
        ),
    ]
