# Generated by Django 4.0.2 on 2022-07-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0030_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('theme', models.TextField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('flier_1', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
