# Generated by Django 4.0.2 on 2022-07-14 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0031_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='img',
        ),
    ]
