# Generated by Django 4.0.2 on 2022-07-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0032_remove_projects_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('link', models.CharField(max_length=500)),
                ('flier_1', models.ImageField(null=True, upload_to='media')),
            ],
        ),
    ]
