# Generated by Django 4.0.2 on 2022-07-14 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0033_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
