# Generated by Django 4.0.2 on 2022-07-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0034_projects_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='description1',
        ),
        migrations.AddField(
            model_name='projects',
            name='description2',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='description3',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
