# Generated by Django 4.0.2 on 2022-07-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0035_rename_description_projects_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='caption',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
