# Generated by Django 4.0.2 on 2022-07-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0036_projects_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description1',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description2',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description3',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
