# Generated by Django 4.0.2 on 2022-07-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0037_alter_projects_description1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='description1',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description2',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description3',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
