# Generated by Django 4.0.2 on 2022-10-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0039_alter_grant_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fully_Funded_Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('pic', models.ImageField(upload_to='media')),
                ('description', models.TextField(max_length=30000)),
                ('link', models.CharField(max_length=300)),
                ('deadline', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job_vacancies',
            name='id_name',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
